### PR TITLE
Bipt 43 RFC submit button

### PR DESCRIPTION
**Pull request by abdulmalik97**
Related Ticket:

https://eyblockchain.atlassian.net/browse/BIPT-43

Description:

1. Added the ability to submit a proposal for RFC. 
2. Also changed the proposal schema to fit with the new RFC implementation.
3. Created validations for input fields

Screenshot: 
image

Instructions to View:

cd eybc-bip
git pull
git checkout bipt-43-rfc
npm run dev
Pull up localhost:3000 in browser
Click new Proposal
Enter required fields and submit for RFC.

### CODE REVIEW

**Comment by meaghanfitzgerald** [comment]
Can you please include some screenshots of the front-end in this pr?
Please confirm that `npm run build` is successful

**Comment by abdulmalik97** [comment]
> Can you please include some screenshots of the front-end in this pr? Please confirm that `npm run build` is successful

Yes, npm run build was successful.

**Comment by meaghanfitzgerald** [comment]
image
image

Lets remove this field from view, as the proposer should not be able to manually change the status of their proposal. This will be handled automatically during the RFC period, and by the BIP team at the time of a verdict. 

The user should only be able to "Save as draft" and "Submit for RFC"

**Comment by meaghanfitzgerald** [comment]
When not all fields are populated, the user is unable to submit to RFC (which is great!) However, there is nothing prompting the user that all fields **need** to be filled out in order to submit for RFC, so please add one of the following:

Option 1: A note at the top of the page saying '*All fields must be filled out in order to submit for RFC'
Option 2: Disable the "Submit to RFC" button unless all fields are populated
Option 3: If the user tries to submit and fails, add a pop up error message stating '*All fields must be filled out in order to submit for RFC'

**Comment by abdulmalik97** [comment]
@meaghanfitzgerald  I have pushed the changes. Please let me know why vercel is failing. The local build works fine.

**Comment by meaghanfitzgerald** [comment]
@abdulmalik97 it's just due to changes in the prisma schema, should be fixed with a refresh.
@aj-may can you refresh the vercel deployment?

**Comment by aj-may** [comment]
Done

**Comment by aj-may** [comment]
#### 📝 Changed routes:


| [**/new**](https://eybc-h3sni9wit-ajmay.vercel.app/new) |
|:-:|
|<a href="https://eybc-h3sni9wit-ajmay.vercel.app/new">Screenshot of /new</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ywFqh-s4rdmB4W6qT5115duQNEyzP_zmR-R0GixgHtnQR6syrU_xxK1Viv4ZjoeFmboDlO3IiDJ1bXYT_LdTOg.png">(view full size)</a> |



And 1 other route:
- [**/api/proposals**](https://eybc-h3sni9wit-ajmay.vercel.app/api/proposals)



Commit cd03f0caed8b3ac3d1b42235784d7e4402c55af5 (https://eybc-h3sni9wit-ajmay.vercel.app).

**Review by meaghanfitzgerald — APPROVED** [review]
LGTM

**Review by Lana-Butorovic — APPROVED** [review]

**Comment by meaghanfitzgerald** [comment]
👏 👏 really great work!

**Pull request merged**
