### PR TITLE
BIP 73 Loading Indicators

### PR DESCRIPTION
**Pull request by Lana-Butorovic**
### Related Ticket

<https://eyblockchain.atlassian.net/jira/software/projects/BIPT/boards/301/backlog?selectedIssue=BIPT-73>

#### Dependent PR's

N/A

### Description

This PR adds loading indicators to three pages that show up before data (proposal data) is fetched: draft, voting, and rfc. The indicator styling was taken from [this](https://dev.to/afif/i-made-100-css-loaders-for-your-next-project-4eje) link and the styling was done in consultation with Kacey. I created a separate component called Loading that uses this styling so that we can re-use it for any part of the app:

Screen Shot 2023-01-24 at 3 25 43 PM

Styling is included in spinner.css file:
Screen Shot 2023-01-24 at 3 26 36 PM

Changes were made in the exact same way in all three pages. This is an example taken from the voting page:

Screen Shot 2023-01-24 at 3 27 22 PM

The final product looks like this:

Screen Shot 2023-01-24 at 3 30 11 PM

The intent is for this loading indicator to be added to all pages once they are built out (so Accepted and Rejected as well).

### QA Instructions

- [ ] Run the app
- [ ] Check out to branch bip73-loadingIndicators
- [ ] Navigate to Draft page and look for loading indicator
- [ ] Navigate to RFC page and look for loading indicator
- [ ] Navigate to Voting page and look for loading indicator

### Checklist

- [x] I have reviewed the code changes myself
- [x] My code meets all of the acceptance criteria of the ticket it closes.
- [x] I have removed unused code (e.g., `console.logs`, commented out blocks, etc.)
- [ ] I have made all necessary changes to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Any dependent changes have been merged and published.
- [x] Check PR title name is correct.

### CODE REVIEW

**Comment by aj-may** [comment]
#### 📝 Changed routes:


| [**/draft**](https://eybc-lxuihi3em-ajmay.vercel.app/draft) | [**/rfc**](https://eybc-lxuihi3em-ajmay.vercel.app/rfc) |
|:-:|:-:|
|<a href="https://eybc-lxuihi3em-ajmay.vercel.app/draft">Screenshot of /draft</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ryxinyV4tCmFPBfFVMm2fAb2K2bn_TtmSzWLBv4yEI1Nngv7t0cTl--VN1_8rJRPpUiVFWCfv46yvOx1v6nkzw.png">(view full size)</a> |<a href="https://eybc-lxuihi3em-ajmay.vercel.app/rfc">Screenshot of /rfc</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/TKiS66TQSzc-7KE14O8XeU_EooTcmPXvtsd7Yyunwj8ASJZ2ynwQMWq5Wg-1ISubPg9ikLhsZHryxY3eTDSFDw.png">(view full size)</a> |



| [**/voting**](https://eybc-lxuihi3em-ajmay.vercel.app/voting) |
|:-:|
|<a href="https://eybc-lxuihi3em-ajmay.vercel.app/voting">Screenshot of /voting</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/MurBw9bQy7U5pHpcdhjGan0pckvnnwHpAVvHXeUz2dajtNeD8RRN-5PhryEsYhe-rkpdw2TK3sX-FOsWtnEHKQ.png">(view full size)</a> |







Commit dc8cc094821e302d4fcbd0352aa39fc2eecc26c2 (https://eybc-lxuihi3em-ajmay.vercel.app).

**Comment by abdulmalik97** [comment]
@Lana-Butorovic 
Is it possible to add loading indicator logic for "Accepted" and "Rejected" pages as well. That would mean adding their own `useProposalByStatus` call and using the isLoading boolean. 

Also, can you restyle the "No Proposal" that renders when there are no proposals in the list? - Ideally a bigger font and in the center. 

These changes will make it a single PR with all the loading changes taken into account.

**Comment by meaghanfitzgerald** [comment]
QQ: Is there a specific nuance to our app that I am overlooking that requires us to create a component file and style it with it's own CSS? Chakra-UI has a spinner component that has customizable attributes that we can fine tune for stylistic purposes. You can find the documentation here: https://chakra-ui.com/docs/components/spinner

Otherwise the use of a ternary on each page to show the spinner until the `proposalRow`s load should be great!

**Comment by Lana-Butorovic** [comment]
@abdulmalik97 will address your comment ASAP - thank you!

@meaghanfitzgerald addressed this on Slack :)

**Comment by abdulmalik97** [comment]
@Lana-Butorovic  Although, I see code to prettify the "No RFC Proposals" text to make it center. I dont seem to see while running local --

image

**Review by abdulmalik97 — APPROVED** [review]

**Comment by meaghanfitzgerald** [comment]
> @Lana-Butorovic Although, I see code to prettify the "No RFC Proposals" text to make it center. I dont seem to see while running local --

I think this can be quickly fixed by replacing the `<Box>` component with a `<Center>` component documented [here](https://chakra-ui.com/docs/components/center)

Otherwise Lgtm! Will approve once the centering is corrected.

**Comment by Lana-Butorovic** [comment]
@meaghanfitzgerald @abdulmalik97 Changed component to Center from Box - should be good to go now :)

**Pull request merged**
